server:
  port: 8090
---
context: /info
---
spring:
  h2:
    console:
      enabled : true
      path : /h2
  profiles: default
  datasource:
    url: jdbc:h2:file:~/info
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto : update
  application:
    name: com.trail.sample